blog/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='blog_index'), #http://127.0.0.1/blog/
    re_path(r'^(?P<blog_id>[0-9]+)/$',views.detail, name='blog_detail'),
    re_path(r'^category/(?P<category_id>[0-9]+)/$',views.category, name='blog_category'),
    re_path(r'^tag/(?P<tag_id>[0-9]+)/$',views.tag, name='blog_tag'),
    re_path(r'^search/$', views.search, name='blog_search'),
    re_path(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',views.archives, name='blog_archives')
]

website/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from blog.feed import LatestEntriesFeed
from blog import views as blog_views
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry

info_dict = {
    'queryset':Entry.objects.all(),
    'date_field':'modified_date',
}


urlpatterns = [
    path('',blog_views.index),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    re_path(r'^latest/feed/$',LatestEntriesFeed()),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemap':{'blog':GenericSitemap(info_dict, priority=0.6)}},
            name='django.contrib.sitemaps.views.sitemap'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler403 = blog_views.permission_denied
handler404 = blog_views.page_not_found
handler500 = blog_views.page_error

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.urls import reverse


class Category(models.Model):

    name = models.CharField(max_length=128, verbose_name='博客分類')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '博客分類'
        verbose_name_plural = '博客分類'

class Tag(models.Model):

    name = models.CharField(max_length=128, verbose_name='博客標籤')

    def __str__(self):
        return self.name
    class Meta:
        verbose_name = '博客標籤'
        verbose_name_plural = '博客標籤'

class Entry(models.Model):
    title = models.CharField(max_length=128, verbose_name='文章標題')
    author = models.ForeignKey(User, verbose_name='博客作者', on_delete=models.CASCADE)
    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='博客配圖')
    body = models.TextField(verbose_name='博客正文')
    abstract = models.TextField(max_length=256, blank=True, null=True, verbose_name='博客摘要')
    visiting = models.PositiveIntegerField(default=0, verbose_name='博客訪問量')
    category = models.ManyToManyField('Category', verbose_name='博客分類')
    tags = models.ManyToManyField('Tag', verbose_name='博客標籤')
    created_time = models.DateTimeField(auto_now_add=True, verbose_name='創建時間')
    modified_time = models.DateTimeField(auto_now=True, verbose_name='創建時間')
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs={'blog_id':self.id}) #http://127.0.0.1/blog/3
    def increase_visting(self):
        self.visiting+=1
        self.save(update_fields=['visiting'])
    class Meta:
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

blog/views.py
from django.shortcuts import render,get_object_or_404
from . import models
import markdown
import pygments
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import Q
# Create your views here.

def make_paginator(objects, page, num=5):
    paginator = Paginator(objects, num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator

def pagination_data(paginator, page):
    """
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    """
    if paginator.num_pages == 1:
        # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        return {}
    # 当前页左边连续的页码号，初始值为空
    left = []

    # 当前页右边连续的页码号，初始值为空
    right = []

    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False

    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False

    # 标示是否需要显示第 1 页的页码号。
    # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    # 其它情况下第一页的页码是始终需要显示的。
    # 初始值为 False
    first = False

    # 标示是否需要显示最后一页的页码号。
    # 需要此指示变量的理由和上面相同。
    last = False

    # 获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    # 获得分页后的总页数
    total_pages = paginator.num_pages

    # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    page_range = paginator.page_range

    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
        # 此时只要获取当前页右边的连续页码号，
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        right = page_range[page_number:page_number + 4]

        # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
        if right[-1] < total_pages - 1:
            right_has_more = True

        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
        # 此时只要获取当前页左边的连续页码号。
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

        # 如果最左边的页码号比第 2 页页码号还大，
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
        if left[0] > 2:
            left_has_more = True

        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]

        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    data = {
        'left': left,
        'right': right,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'first': first,
        'last': last,
    }
    return data

def index(request):
    entries = models.Entry.objects.all()
    page = request.GET.get('page',1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request,'blog/index.html', locals())



def detail(request,blog_id):
    # entry = models.Entry.objects.get(id=blog_id)
    entry = get_object_or_404(models.Entry, id=blog_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc'
    ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc
    entry.increase_visting()

    return render(request,'blog/detail.html', locals())

def category(request, category_id):
    # c = models.Category.objects.get(id=category_id)
    c = get_object_or_404(models.Entry, id=category_id)
    entries = models.Entry.objects.filter(category=c)
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def tag(request, tag_id):
    t = models.Tag.objects.get(id=tag_id)
    if t.name == '全部':
        entries = models.Entry.objects.all()
    else:
        entries = models.Entry.objects.filter(tags=t)

    page = request.GET.get('page',1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def search(request):
    keyword = request.GET.get('keyword', None)
    if not keyword:
        error_msg = '請輸入關鍵字'
        return render(request, 'blog/index.html', locals())
    entries = models.Entry.objects.filter(Q(title__icontains=keyword)
                                          |Q(body__icontains=keyword)
                                          |Q(abstract__icontains=keyword))

    page = request.GET.get('page',1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())

def archives(request,year,month):
    entries = models.Entry.objects.filter(created_time__year=year, created_time__month=month)
    page = request.GET.get('page',1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def permission_denied(request, template_name='blog/403.html'):

    return render(request, template_name, locals())

def page_not_found(request, template_name='blog/403.html'):

    return render(request, template_name, locals())

def page_error(request, template_name='blog/500.html'):

    return render(request, template_name, locals())

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}基本模板{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/blog_nav.css' %}" rel="stylesheet">
    {% block css %}

    {% endblock %}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  <nav class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><img src="{% static 'blog/img/rocket.jpg' %}" alt=""/><span class="navbar-text">我的博客</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="my-nav">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/blog/">博客</a></li>
          <li><a href="#">關於博主</a></li>
          <li><a href="#">聯繫我們</a></li>
      </ul>
      <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}" method="get">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="keyword">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">登入</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  {% block content %}

  {% endblock %}
   <footer>
    <div class="footer" role="navigation">
        <div class="container">
            <div class="navbar-text">
                <ul class="footer-text">
                    <li><a href="#">主業</a></li>
                    <li><a href="#" target="_blank">聯繫我們</a></li>
                    <li><a href="#">關於博主</a></li>
                    <li><a href="#" target="_blank">文檔支持</a></li>
                    <li><a href="/blog/">博客首頁</a></li>
                    <!--2019-07-11 20:16:25 +0000-->
                </ul>
                <p>Copyright © 2019  Project Jupyter – 黃煜展的博客</p>
            </div>
        </div>
    </div>

       <div id="back-to-top">
           <i class="glyphicon glyphicon-arrow-up"></i>
       </div>

</footer>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  <script>
      $('#back-to-top').click(function(){
         window.scrollTo(0,0)
      });
  </script>
    {% block script %}
    {% endblock %}
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block title %}博客詳細頁面{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'blog/css/github.css' %}"/>
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
            <h1>{{ entry.title }}</h1>
                <p><strong>{{ entry.author }}</strong>
                &nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日' }}
                &nbsp;&nbsp;&nbsp;&nbsp;分類:
                    {% for category in entry.category.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                    {% endfor %}
                &nbsp;&nbsp;&nbsp;&nbsp;標籤:
                    {% for tag in entry.tags.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}
                &nbsp;&nbsp;&nbsp;&nbsp;瀏覽量:
                    &nbsp;&nbsp;{{ entry.visiting }}
                </p>
                    {% if entry.img %}
            <div><img src="{{ entry.img.url }}" alt="博客配圖" width="100%"></div>
        {% endif %}
                <br>
            <p>
                {{ entry.body|safe }}
            </p>
        </div>
            <div class="col-md-3">
                {% block toc %}
                    <div class="row">
                    <div class="widget">
                    <h3>博客目錄</h3>
                        {{ entry.toc|safe }}
                    </div>
                    </div>
                {% endblock %}
            {% include 'blog/right_side_bar.html' %}
        </div>
    </div>

    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}博客首頁{% endblock %}
{% block content %}
<div class="container">
<div class="row">
<div class="col-md-9">
    {% for entry in entry_list %}
        <br>
        <h2><a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a></h2>
        {% if entry.img %}
            <div><img src="{{ entry.img.url }}" alt="博客配圖" width="100%"></div>
        {% endif %}
        {% if entry.abstract %}
        <p>{{ entry.abstract }}</p>
        {% else %}
        <p>{{ entry.body|truncatechars:64 }}</p>
        {% endif %}
        <p>
            <span>作者: {{ entry.author }}</span>
            <span>&nbsp;&nbsp;&nbsp;&nbsp;發表時間: {{ entry.created_time }}</span>
            <span>&nbsp;&nbsp;&nbsp;&nbsp;訪問量: {{ entry.visiting }}</span>
        </p>
    {% endfor %}
                <!--/.pagination-->
            <div id="paginator" class="pull-right">
                <ul class="pagination">
                {%  if entry_list.has_previous %}
                    <li><a href="?page={{ entry_list.previous_page_number }}"><i class="glyphicon glyphicon-chevron-left"></i>前一页</a></li>
                {% endif %}

                {% if first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}

                {% if left %}
                    {% if left_has_more %}
                        <span>...</span>
                    {% endif %}

                    {% for i in left %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}


                <li class="active"><a href="?page={{ entry_list.number }}">{{ entry_list.number }}</a></li>

                {% if right %}
                    {% for i in right %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}

                    {% if right_has_more %}
                        <span>...</span>
                    {% endif %}
                {% endif %}

                {% if last %}
                    <li><a href="?page={{ entry_list.num_pages }}">{{ entry_list.num_pages }}</a></li>
                {% endif %}

                {% if entry_list.has_next %}
                    <li><a href="?page={{ entry_list.next_page_number }}">下一页<i class="glyphicon glyphicon-chevron-right"></i></a></li>
                {% endif %}
                </ul>
            </div>
        </div>

        <div class="col-md-3">
            {% include 'blog/right_side_bar.html' %}
        </div>
    </div>

    </div>

{% endblock %}

blog/templates/blog/right_side_bar.html
{% load blog_tags %}
{% block toc %}

{% endblock %}
<div class="row">
    <div class="widget">
        <h3>最新博客</h3>
        {% get_recent_entries as recent_entry_list %}

        {% for entry in recent_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <div>{{ entry.author }} 發表於: {{ entry.created_time|date:'Y年m月d日 f' }}</div>
            </div>
        {% endfor %}
    </div>
</div>
<hr/>
<div class="row">
    <div class="widget">
        <h3>推薦博客</h3>
        {% get_popular_entries as popular_entry_list %}

        {% for entry in recent_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <span class="badge">{{ entry.visiting }}</span>
            </div>
        {% endfor %}
    </div>
</div>
<hr/>
<div class="row">
    <div class="widget">
        <h3>分類:</h3>
        {% get_category as category_list %}
        <ul class="list-group">
            {% for category in category_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                <span class="badge">{% get_entry_count_of_category category.name %}</span>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
<hr/>
<div class="row">
    <div class="widget">
        <h3>歸檔:</h3>
        {% archives as date_list %}
        <ul class="list-group">
            {% for date in date_list %}
                <li class="list-group-item">
                <a href="{% url 'blog:blog_archives' date.year date.month %}">
                <i class='glyphicon glyphicon-chevron-right'></i>
                    {{ date.year }}年{{ date.month }}月
                    <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                </a>
                </li>
        {% endfor %}
        </ul>
    </div>
</div>
<hr/>
<div class="row">
    <div class="widget">
        <h3>標籤雲:</h3>
        {% get_tags as tag_list %}
            {% for tag in tag_list %}
                    <a href="{% url 'blog:blog_tag' tag.id %}">
                        <span class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}">{{ tag.name }}</span>
                    </a>
        {% endfor %}
    </div>
</div>
<hr/>
<div class="row">
    <div class="rss">
        <a href="/latest/feed/"><i class="glyphicon glyphicon-heart"></i>RSS訂閱</a>
    </div>
</div>